# Generated by Django 5.0.7 on 2024-08-03 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_remove_apk_apk_path_apk_apk_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apk',
            options={'verbose_name': '安装包管理', 'verbose_name_plural': '安装包管理'},
        ),
        migrations.AlterModelOptions(
            name='distributionproject',
            options={'verbose_name': 'APP注册', 'verbose_name_plural': 'APP注册'},
        ),
        migrations.AlterField(
            model_name='apk',
            name='apk_file',
            field=models.FileField(upload_to='apks/', verbose_name='apk文件'),
        ),
        migrations.AlterField(
            model_name='apk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apks', to='distributions.distributionproject', verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='apk',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='distributionproject',
            name='description',
            field=models.TextField(verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='distributionproject',
            name='package_name',
            field=models.CharField(max_length=255, verbose_name='项目包名'),
        ),
    ]
