# Generated by Django 5.0.7 on 2024-08-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_clientlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_android_api',
            field=models.CharField(default=34, max_length=255, verbose_name='客户端API版本'),
            preserve_default=False,
        ),
    ]
