# Generated by Django 5.0.7 on 2024-08-03 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_clientlog_options_and_more'),
        ('distributions', '0003_alter_apk_options_alter_distributionproject_options_and_more'),
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': '发布终端', 'verbose_name_plural': '发布终端'},
        ),
        migrations.AlterField(
            model_name='terminal',
            name='description',
            field=models.TextField(verbose_name='发布终端描述'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='发布终端暂停'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='location',
            field=models.TextField(verbose_name='发布终端位置'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminal_code',
            field=models.CharField(max_length=100, verbose_name='发布终端代码'),
        ),
        migrations.CreateModel(
            name='TerminalApkDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distributions.apk', verbose_name='激活安装包')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.terminal', verbose_name='发布终端')),
            ],
            options={
                'verbose_name': '发布终端-安装包分发',
                'verbose_name_plural': '发布终端-安装包分发',
            },
        ),
        migrations.CreateModel(
            name='TerminalClientBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='客户端')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.terminal', verbose_name='发布终端')),
            ],
            options={
                'verbose_name': '发布终端-客户端绑定',
                'verbose_name_plural': '发布终端-客户端绑定',
            },
        ),
    ]
