# Generated by Django 5.0.7 on 2024-08-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0002_alter_terminal_options_alter_terminal_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalapkdistribution',
            options={'verbose_name': '安装包分发', 'verbose_name_plural': '安装包分发'},
        ),
        migrations.AlterModelOptions(
            name='terminalclientbinding',
            options={'verbose_name': '终端-实体绑定', 'verbose_name_plural': '终端-实体绑定'},
        ),
    ]
