# Generated by Django 5.0.7 on 2024-08-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0003_alter_apk_options_alter_distributionproject_options_and_more'),
        ('terminals', '0003_alter_terminalapkdistribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalapkdistribution',
            name='apk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributions.apk', verbose_name='激活安装包'),
        ),
        migrations.AlterField(
            model_name='terminalapkdistribution',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.terminal', unique=True, verbose_name='发布终端'),
        ),
    ]
